[features]
seeds = false
skip-lint = false
[programs.localnet]
token = "5ugjDFNtj6UmuP1BCd4kGKFPHJowUWtktxdp8yXxRxf5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/bonani/.config/solana/id.json"
# wallet = "/home/caio/iniacao_cientifica/Solana_token_trade/tests/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
